language:
- objective-c
env:
  global: LATEST_TAG=1
  matrix:
  - VERSION=2.7.8
  - VERSION=3.3.5
  - VERSION=3.4.1
install:
- source terryfy/travis_tools.sh
- get_python_environment macpython $VERSION venv
- pip install wheel
- if [ -n "$LATEST_TAG" ]; then checkout_closest_tag Cython; fi
- cd Cython
- python setup.py bdist_wheel
- rename_wheels dist
- pip install dist/*.whl
- cd ..
script:
- cd Cython
- cython Demos/*.pyx
- require_success "Cythonizing may have failed"
- cd ..
before_deploy: cd Cython/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: ALZrkCwjz3nY/9GfTNPgVQHUmUpCc5SnZTaqIUlJrhVyOBu6aktXaRmQi+sTXzFn7a/PQsYDnoZ8nibCZ472oUVDGUOSbtjIEkPodU+aisLN2dSLNueQsUU7Dmt0SaeyJVGovzfyUiavIYLuAfOtCfUKrwAsi7XTVNQpdyWCQDs=
  region: ORD
  container: wheels
  skip_cleanup: true
